service: BCMAPI
provider:
  name: aws
  runtime: python3.7
functions:
  ReadBCMViewAndPutSQS:
    handler: fetchsql.main


resources:
  Resources:
    BCMQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "BCMQueue"